name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - CloudFoundry

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -O cf-cli.deb https://github.com/cloudfoundry/cli/releases/download/v8.14.0/cf8-cli-installer_8.14.0_x86-64.deb
          sudo dpkg -i cf-cli.deb

      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          ACCESS_TOKENCLOUD: ${{ secrets.ACCESS_TOKENCLOUD }}
        run: |
          cf api "$CF_API"
          cf login --sso-passcode "$ACCESS_TOKENCLOUD"

      - name: Deploy Frontend
        run: |
          cd frontend
          cf push

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -O cf-cli.deb https://github.com/cloudfoundry/cli/releases/download/v8.14.0/cf8-cli-installer_8.14.0_x86-64.deb
          sudo dpkg -i cf-cli.deb

      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          ACCESS_TOKENCLOUD: ${{ secrets.ACCESS_TOKENCLOUD }}
        run: |
          cf api $CF_API
          cf login --sso-passcode $ACCESS_TOKENCLOUD

      - name: Prepare environment variables
        env:
          SERVER_NODE: ${{ secrets.SERVER_NODE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BACK_PORT: ${{ secrets.BACK_PORT }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: |
          echo "Environment variables set dynamically from GitHub secrets."

      - name: Deploy Backend
        run: |
          cd backend
          cf push