name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -O cf-cli.deb https://packages.cloudfoundry.org/stable?release=debian64&source=github
          sudo dpkg -i cf-cli.deb

      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          ACCESS_TOKENCLOUD: ${{ secrets.ACCESS_TOKENCLOUD }}
        run: |
          cf api $CF_API
          cf auth --bearer $ACCESS_TOKENCLOUD

      - name: Deploy Frontend
        run: |
          cd frontend
          cf push

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -O cf-cli.deb https://packages.cloudfoundry.org/stable?release=debian64&source=github
          sudo dpkg -i cf-cli.deb

      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          ACCESS_TOKENCLOUD: ${{ secrets.ACCESS_TOKENCLOUD }}
        run: |
          cf api $CF_API
          cf auth --bearer $ACCESS_TOKENCLOUD

      - name: Prepare vars.yml
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          cat <<EOF > backend/vars.yml
          variables:
            SERVER_NODE=4a53890c-d249-478e-a7ab-6e12660c5573.hana.trial-us10.hanacloud.ondemand.com:443
            DB_USERNAME=DBADMIN
            DB_PASSWORD=$DB_PASSWORD
            JWT_SECRET=$JWT_SECRET
            BACK_PORT=5000
            BACKEND_URL=https://sapitos-backend.cfapps.io
            FRONTEND_URL=https://sapitos-frontend.cfapps.us10-001.hana.ondemand.com/
          EOF

      - name: Deploy Backend
        run: |
          cd backend
          cf push --vars-file vars.yml